version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    command: [
      "postgres",
      "-c", "max_connections=200",
      "-c", "listen_addresses=*",
      "-c", "shared_buffers=256MB",
      "-c", "effective_cache_size=1GB",
      "-c", "work_mem=4MB"
    ]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=evolution_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
    - postgres_data:/var/lib/postgresql/data

  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: unless-stopped
    ports:
      - "1880:1880" # Acesse em http://localhost:1880
    volumes:
      - nodered_data:/data
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - influxdb

  influxdb:
    container_name: influxdb
    image: influxdb:2.7
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=UFGInf2025@
      - DOCKER_INFLUXDB_INIT_ORG=UFGInf2025
      - DOCKER_INFLUXDB_INIT_BUCKET=UFG-Weather
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dafda90fasd8f0adsadacsda9s0djdad8a9sd

volumes:
  postgres_data:
  nodered_data:
  influxdb_data:
  influxdb_config:
